version: '2'
services:
    blog-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/blog/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=blog
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
